name = "LatticeKit"
uuid = "c5541aab-fd05-45d9-a9ee-bd64ea018e2d"
authors = ["Jia-heng Ji <1422805255@qq.com>"]
version = "0.1.0"

[deps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
UnicodePlots = "3.8.1"
